###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"satyanarayana",
    "username":"ssatya123",
    "password": "rahul@456",
    "gender": "Male",
    "location":"kuppam"
}


###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"rahul",
    "username":"rahul123",
    "password": "rahul@456",
    "gender": "Male",
    "location":"Bangalore"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"ssatya123",
    "password": "rahul@456"
}